CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  affiliation TEXT NOT NULL CHECK (affiliation IN ('FRIEND','HOSTILE','NEUTRAL')),
  unit_type TEXT NOT NULL CHECK (unit_type IN ('INFANTRY','ARMOR','ARTILLERY','UAS')),
  echelon TEXT NOT NULL CHECK (echelon IN ('SECTION','BATTALION','BRIGADE')),
  sidc TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
