-- Extensions
CREATE EXTENSION IF NOT EXISTS postgis;

-- Units only
CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('FRIEND','ENEMY','NEUTRAL','UNKNOWN')),
  unit_type TEXT NOT NULL CHECK (
    unit_type IN (
      'INFANTRY','ARMOR','ARTILLERY','COMMAND_POST',
      'UAS','UAS_ATTACK','UAS_BOMBER','UAS_CARGO','UAS_COMMAND_POST','UAS_FIGHTER',
      'UAS_CSAR','UAS_JAMMER','UAS_TANKER','UAS_VTOL','UAS_SOF','UAS_MCM','UAS_ASUW',
      'UAS_PATROL','UAS_RECON','UAS_AEW','UAS_ESM','UAS_PHOTOGRAPHIC','UAS_ASW',
      'UAS_TRAINER','UAS_UTILITY','UAS_COMM','UAS_MEDEVAC'
    )
  ),
  echelon TEXT NOT NULL DEFAULT 'SECTION' CHECK (echelon IN ('SECTION','BATTALION','BRIGADE')),
  sidc TEXT NOT NULL DEFAULT 'SFGPUCI----C',
  geom geometry(Point, 4326) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_units_geom ON units USING GIST (geom);
