-- Extensions
CREATE EXTENSION IF NOT EXISTS postgis;

-- Units only
CREATE TABLE IF NOT EXISTS units (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('FRIEND','ENEMY','NEUTRAL')),
  unit_type TEXT NOT NULL CHECK (unit_type IN ('INFANTRY','ARMOR','ARTILLERY','UAS')),
  echelon TEXT NOT NULL DEFAULT 'SECTION' CHECK (echelon IN ('SECTION','BATTALION','BRIGADE')),
  sidc TEXT NOT NULL DEFAULT 'SFGPUCI----K',
  geom geometry(Point, 4326) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_units_geom ON units USING GIST (geom);
